'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    try {
      // Insert artist data
      await queryInterface.sequelize.query(`INSERT INTO member (name,age,gender,position,artist_id) VALUES
      ('Jin',30,'Man','Sub Vocal',1),
      ('SUGA',29,'Man','Lead Rapper',1),
      ('J−HOPE',28,'Man','Sub Rapper, Main Dancer',1),
      ('RM',28,'Man','Leader, Main Rapper',1),
      ('Jimin',27,'Man','Lead Vocal, Main Dancer',1),
      ('V',27,'Man','Sub Vocal',1),
      ('Jungkook',25,'Man','Main Vocal, Sub Rapper, Lead Dancer',1),
      ('YEONJUN',23,'Man','Main Dancer',2),
      ('SOOBIN',22,'Man','Leader',2),
      ('BEOMGYU',21,'Man','Sub Vocal, Lead Dancer',2),
      ('TAEHYUN',20,'Man','Lead Vocal',2),
      ('HUENINGKAI',20,'Man','Main Vocal',2),
      ('Kwon Bo A',36,'Woman','Solo',3),
      ('U-Know Yunho',36,'Man','Leader, Main Dancer, Main Rapper, Lead Vocal',4),
      ('Max Changmin',34,'Man','Main Vocal, Lead Rapper, Lead Dancer',4),
      ('LEETEUK',39,'Man','Leader, Sub Vocal, Sub Rapper',5),
      ('HEECHUL',39,'Man','Sub Vocal, Sub Rapper',5),
      ('YESUNG',38,'Man','Main Vocal',5),
      ('SHINDONG',37,'Man','Lead Dancer, Sub Vocal, Sub Rapper',5),
      ('EUNHYUK',36,'Man','Main Dancer, Main Rapper, Sub Vocal',5),
      ('SIWON',36,'Man','Center, Sub Vocal',5),
      ('DONGHAE',36,'Man','Lead Dancer, Lead Vocal, Sub Rapper',5),
      ('RYEOWOOK',35,'Man','Main Vocal',5),
      ('KYUHYUN',34,'Man','Main Vocal',5),
      ('TAEYEON',33,'Woman','Leader, Main Vocal',6),
      ('SUNNY',33,'Woman','Lead Vocal',6),
      ('TIFFANY',33,'Woman','Lead Vocal',6),
      ('HYOYEON',33,'Woman','Sub Vocal, Main Dancer',6),
      ('YURI',33,'Woman','Sub Vocal, Main Dancer',6),
      ('SOOYOUNG',32,'Woman','Sub Vocal, Lead Dancer',6),
      ('YOONA',32,'Woman','Center, Sub Vocal, Lead Dancer',6),
      ('SEOHYUN',31,'Woman','Lead Vocal',6),
      ('ONEW',33,'Man','Leader, Lead Vocal',7),
      ('KEY',31,'Man','Sub Vocal, Lead Rapper, Lead Dancer',7),
      ('MINHO',31,'Man','Sub Vocal, Main Rapper',7),
      ('TAEMIN',29,'Man','Center, Main Dancer, Lead Vocal',7),
      ('XIUMIN',32,'Man','Sub Vocal, Sub Rapper',8),
      ('SUHO',31,'Man','Leader, Lead Vocal',8),
      ('LAY',31,'Man','Main Dancer, Sub Vocal',8),
      ('BAEKHYUN',30,'Man','Leader, Main Vocal',8),
      ('CHEN',30,'Man','Main Vocal',8),
      ('CHANYEOL',30,'Man','Main Rapper, Sub Vocal',8),
      ('D.O.',29,'Man','Main Vocal',8),
      ('KAI',28,'Man','Main Dancer, Sub Rapper, Sub Vocal',8),
      ('SEHUN',28,'Man','Lead Rapper, Lead Dancer',8),
      ('IRENE',31,'Woman','Center, Leader, Main Rapper, Sub Vocal, Lead Dancer',9),
      ('SEULGI',28,'Woman','Main Dancer, Lead Vocal',9),
      ('WENDY',28,'Woman','Main Vocal',9),
      ('JOY',26,'Woman','Lead Rapper, Sub Vocal',9),
      ('YERI',23,'Woman','Sub Vocal, Sub Rapper',9),
      ('Park Jin Young',51,'Man','Solo',10),
      ('JUN. K',34,'Man','Main Vocal',11),
      ('NICHKHUN',34,'Man','Sub Vocal',11),
      ('TAECYEON',34,'Man','Main Rapper',11),
      ('WOOYOUNG',33,'Man','Main Dancer, Sub Vocal',11),
      ('JUNHO',32,'Man','Lead Vocal, Main Dancer',11),
      ('CHANSUNG',32,'Man','Sub Vocal',11),
      ('SUNGJIN',29,'Man','Leader, Rhythm Guitar, Vocal',12),
      ('Jae',30,'Man','Lead Guitar, Vocal, Rap',12),
      ('Young K',29,'Man','Bass, Vocal, Rap',12),
      ('WONPIL',28,'Man','Synthesizer, Keyboard, Vocal',12),
      ('DOWOON',27,'Man','Drum, Vocal',12),
      ('NAYEON',27,'Woman','Lead Vocal, Lead Dancer',13),
      ('JEONGYEON ',26,'Woman','Lead Vocal',13),
      ('MOMO',26,'Woman','Sub Vocal, Sub Rapper, Main Dancer',13),
      ('SANA ',26,'Woman','Sub Vocal',13),
      ('JIHYO ',25,'Woman','Leader, Main Vocal',13),
      ('MINA',25,'Woman','Sub Vocal, Main Dancer',13),
      ('DAHYUN',24,'Woman','Lead Rapper, Sub Vocal',13),
      ('CHAEYOUNG',23,'Woman','Main Rapper, Sub Vocal',13),
      ('TZUYU',23,'Woman','Sub Vocal, Lead Dancer',13),
      ('BANG CHAN',25,'Man','Leader, Producer, Vocal, Rapper, Dancer',14),
      ('LEE KNOW',24,'Man','Vocal, Rapper, Dancer',14),
      ('CHANGBIN',23,'Man','Vocal, Rapper, Producer',14),
      ('HYUNJIN',22,'Man','Rapper, Dancer',14),
      ('HAN',22,'Man','Vocal, Rapper, Producer',14),
      ('FELIX',22,'Man','Rapper, Dancer',14),
      ('SEUNGMIN',22,'Man','Vocal',14),
      ('I.N',21,'Man','Vocal',14),
      ('YEJi',22,'Woman','Leader, Main Dancer, Lead Vocal, Sub Rapper',15),
      ('LiA',22,'Woman','Main Vocal',15),
      ('RYUJiN',21,'Woman','Center, Main Rapper, Sub Vocal, Lead Dancer',15),
      ('CHAERYEONG',21,'Woman','Main Dancer, Sub Vocal, Sub Rapper',15),
      ('YUNA',19,'Woman','Sub Vocal, Sub Rapper',15),
      ('T.O.P',35,'Man','Lead Rapper, Sub Vocal',16),
      ('TAEYANG',34,'Man','Main Vocal, Main Dancer, Sub Rapper',16),
      ('G-DRAGON',34,'Man','Leader, Main Rapper, Sub Vocal',16),
      ('DAESUNG',33,'Man','Lead Vocal',16),
      ('JINU',31,'Man','Lead Vocal',17),
      ('HOONY',30,'Man','Main Dancer, Lead Rapper, Sub Vocal',17),
      ('MINO',29,'Man','Main Rapper, Sub Vocal',17),
      ('YOON',28,'Man','Leader, Main Vocal, Main Producer',17),
      ('JAY',28,'Man','Main Vocal, Lead Dancer',18),
      ('SONG',27,'Man','Sub Vocal',18),
      ('BOBBY',27,'Man','Main Rapper, Sub Vocal',18),
      ('DK',25,'Man','Sub Vocal, Main Dancer',18),
      ('JU-NE',25,'Man','Main Vocal',18),
      ('CHAN',24,'Man','Sub Vocal',18),
      ('JISOO',27,'Woman','Lead Vocal',19),
      ('JENNIE',26,'Woman','Main Rapper, Lead Vocal',19),
      ('ROSÉ',25,'Woman','Main Vocal, Lead Dancer',19),
      ('LISA',25,'Woman','Main Dancer, Lead Rapper, Sub Vocal',19);`);

      return Promise.resolve();
    } catch (e) {
      return Promise.reject(e);
    }
  },
  down: async (queryInterface, Sequelize) => {
  }
};